/// Turns a RustaBase schema (the list returned by `GET /api/collections`)
/// into Dart model classes. Pure: no network or file access, so it can be
/// used from build scripts and tests.
library;

Object? _opt(Map<String, dynamic> field, String key) {
  if (field.containsKey(key)) return field[key];
  final options = field["options"];
  return options is Map ? options[key] : null;
}

bool _many(Map<String, dynamic> field) {
  final v = _opt(field, "maxSelect");
  return v is num && v > 1;
}

const _reserved = {
  "abstract", "as", "assert", "async", "await", "break", "case", "catch", //
  "class", "const", "continue", "default", "do", "dynamic", "else", "enum",
  "export", "extends", "extension", "external", "factory", "false", "final",
  "finally", "for", "get", "if", "implements", "import", "in", "interface",
  "is", "late", "library", "mixin", "new", "null", "operator", "part",
  "required", "rethrow", "return", "set", "static", "super", "switch", "this",
  "throw", "true", "try", "typedef", "var", "void", "while", "with", "yield",
};

List<String> _words(String name) =>
    name.split(RegExp(r"[^A-Za-z0-9]+")).where((w) => w.isNotEmpty).toList();

/// `blog_posts` -> `BlogPosts`.
String pascalCase(String name) {
  final out =
      _words(name).map((w) => w[0].toUpperCase() + w.substring(1)).join();
  if (out.isEmpty) return "Table";
  return RegExp(r"^[0-9]").hasMatch(out) ? "T$out" : out;
}

/// `created_at` -> `createdAt`; Dart keywords get a trailing `_`.
String camelCase(String name) {
  final p = pascalCase(name);
  var out = p[0].toLowerCase() + p.substring(1);
  if (RegExp(r"^t[0-9]").hasMatch(out)) out = "f${out.substring(1)}";
  return _reserved.contains(out) ? "${out}_" : out;
}

/// A Dart string literal holding [s].
String _lit(String s) {
  final body =
      s.replaceAll(r"\", r"\\").replaceAll('"', r'\"').replaceAll(r"$", r"\$");
  return '"$body"';
}

class _Col {
  _Col(this.name, this.prop, this.type, this.read);
  final String name;
  final String prop;
  final String type; // Dart type of the property
  final String read; // expression reading `v` from JSON
}

const _str = "v?.toString() ?? \"\"";
const _list = "(v as List?)?.map((e) => e.toString()).toList() ?? const []";

_Col _column(Map<String, dynamic> f) {
  final name = f["name"] as String;
  final prop = camelCase(name);
  switch (f["type"]) {
    case "number":
      return _Col(name, prop, "num", "(v as num?) ?? 0");
    case "bool":
      return _Col(name, prop, "bool", "v == true");
    case "json":
      return _Col(name, prop, "Object?", "v");
    case "geoPoint":
    case "geopoint":
      return _Col(
        name,
        prop,
        "Map<String, num>",
        "(v as Map?)?.cast<String, num>() ?? const {}",
      );
    case "select":
    case "file":
    case "relation":
      return _many(f)
          ? _Col(name, prop, "List<String>", _list)
          : _Col(name, prop, "String", _str);
    default:
      return _Col(name, prop, "String", _str);
  }
}

List<Map<String, dynamic>> _maps(Object? list) => list is List
    ? list
        .whereType<Map<dynamic, dynamic>>()
        .map((m) => m.cast<String, dynamic>())
        .toList()
    : const [];

/// Generates the Dart source for [collections]. System tables are skipped
/// unless [includeSystem] is true.
String generateDartTypes(
  List<dynamic> collections, {
  bool includeSystem = false,
}) {
  final list = _maps(collections)
      .where(
        (c) => c["name"] is String && (includeSystem || c["system"] != true),
      )
      .toList()
    ..sort((a, b) => (a["name"] as String).compareTo(b["name"] as String));

  final b = StringBuffer()
    ..writeln(
      "// Generated by `dart run rustabase:gen_types`. Do not edit by hand;",
    )
    ..writeln("// run the command again after changing your tables.")
    ..writeln("// ignore_for_file: type=lint")
    ..writeln();

  final names = <String, String>{};
  for (final c in list) {
    final table = c["name"] as String;
    final cls = pascalCase(table);
    names[table] = cls;
    final fields = _maps(c["fields"])
        .where(
          (f) =>
              f["name"] is String &&
              f["type"] != "password" &&
              f["hidden"] != true,
        )
        .toList();
    final cols = <_Col>[
      if (!fields.any((f) => f["name"] == "id"))
        _Col("id", "id", "String", _str),
      ...fields.map(_column),
    ];

    b
      ..writeln("/// Row of the `$table` table (${c["type"] ?? "base"}).")
      ..writeln("class $cls {")
      ..writeln("  const $cls({");
    for (final x in cols) {
      b.writeln("    required this.${x.prop},");
    }
    b
      ..writeln("    this.expand = const {},")
      ..writeln("  });")
      ..writeln()
      ..writeln("  /// Table name on the server.")
      ..writeln("  static const tableName = ${_lit(table)};")
      ..writeln();
    for (final x in cols) {
      b.writeln("  final ${x.type} ${x.prop};");
    }
    b
      ..writeln("  final Map<String, dynamic> expand;")
      ..writeln()
      ..writeln("  factory $cls.fromJson(Map<String, dynamic> json) => $cls(");
    for (final x in cols) {
      final v = "json[${_lit(x.name)}]";
      b.writeln(
        "        ${x.prop}: ${x.read.replaceAll(RegExp(r"\bv\b"), v)},",
      );
    }
    b
      ..writeln(
        "        expand: (json[\"expand\"] as Map?)?.cast<String, dynamic>() ?? const {},",
      )
      ..writeln("      );")
      ..writeln()
      ..writeln("  Map<String, dynamic> toJson() => {");
    for (final x in cols) {
      b.writeln("        ${_lit(x.name)}: ${x.prop},");
    }
    b
      ..writeln("      };")
      ..writeln("}")
      ..writeln();
  }

  b
    ..writeln("/// Every generated table: name -> JSON decoder.")
    ..writeln(
      "const Map<String, Object Function(Map<String, dynamic>)> rustabaseTables = {",
    );
  names.forEach((table, cls) => b.writeln("  ${_lit(table)}: $cls.fromJson,"));
  b.writeln("};");
  return b.toString();
}
